add mysql service on deploymentjob

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,53 +45,52 @@ jobs:
             sleep 2
           done
           echo "MySQL did not become available in time" && exit 1
+  # deploy:
+  #   needs: test
+  #   services:
+  #     mysql:
+  #       image: mysql:8.0
+  #       ports:
+  #         - 3306:3306
+  #       env:
+  #         MYSQL_ROOT_PASSWORD: root
+  #         MYSQL_DATABASE: books
+  #       options: >-
+  #         --health-cmd="mysqladmin ping -h localhost --silent"
+  #         --health-interval=10s
+  #         --health-timeout=5s
+  #         --health-retries=3
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-  deploy:
-    needs: test
-    services:
-      mysql:
-        image: mysql:8.0
-        ports:
-          - 3306:3306
-        env:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: books
-        options: >-
-          --health-cmd="mysqladmin ping -h localhost --silent"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=3
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     - name: Setup Go
+  #       uses: actions/setup-go@v5
+  #       with:
+  #         go-version: '^1.13.1'
 
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: '^1.13.1'
+  #     - name: Run Mod
+  #       run: go mod tidy
 
-      - name: Run Mod
-        run: go mod tidy
+  #     - name: Wait for MySQL
+  #       run: |
+  #         for i in {1..30}; do
+  #           if mysqladmin ping -h 127.0.0.1  -P 3306 --silent; then
+  #             echo "MySQL is up and running"
+  #             exit 0
+  #           fi
+  #           echo "Waiting for MySQL..."
+  #           sleep 2
+  #         done
+  #         echo "MySQL did not become available in time" && exit 1
 
-      - name: Wait for MySQL
-        run: |
-          for i in {1..30}; do
-            if mysqladmin ping -h 127.0.0.1  -P 3306 --silent; then
-              echo "MySQL is up and running"
-              exit 0
-            fi
-            echo "Waiting for MySQL..."
-            sleep 2
-          done
-          echo "MySQL did not become available in time" && exit 1
+  #     - name: Build and deploy
+  #       run: |
+  #         go build -o main ./cmd/main
 
-      - name: Build and deploy
-        run: |
-          go build -o main ./cmd/main
-
-      - name: Run Application
-        env:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: books
-        run: ./main
+  #     - name: Run Application
+  #       env:
+  #         MYSQL_ROOT_PASSWORD: root
+  #         MYSQL_DATABASE: books
+  #       run: ./main
